# Change these first
owner: sensein # Your GitHub organization or username, where this repository lives
repo: Neuro-Ontologies # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
