# Change these first
owner: sensein 
repo: Neuro-Ontologies 

sites:
  - name: Cognitive Atlas
    url: https://www.cognitiveatlas.org/
  - name: Clements Checklist
    url: https://www.birds.cornell.edu/clementschecklist/introduction/updateindex/october-2024/2024-citation-checklist-downloads/
  - name: Trust for Avian Systematics
    url: https://www.aviansystematics.org/
  - name: Birds of the World
    url: https://birdsoftheworld.org/bow/home
